const actionType = {
  TASK_LOADING: "TASK_LOADING",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILURE: "FETCH_TASKS_FAILURE",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_FAILURE: "ADD_TASK_FAILURE",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE"
};

export default actionType;
