const actionType = {
  AUTH_LOADING: "AUTH_LOADING",
  FETCH_USER_AUTH_SUCCESS: "FETCH_USER_AUTH_SUCCESS",
  FETCH_USER_AUTH_FAILURE: "FETCH_USER_AUTH_FAILURE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT"
};

export default actionType;
